### PR TITLE
php 8.1 compat

### PR DESCRIPTION
**Pull request by ryco-dev**
Signed-off-by: Ryan Coe <bluemrp9@gmail.com>

### CODE REVIEW

**Comment by sebastianwos** [comment]
Any chance to merge this PR ?

**Comment by ronfoerster** [comment]
@mgdm Please merge this commit to the php8 branch!

**Comment by decole** [comment]
@mgdm Please merge this commit to the php8 branch!

**Comment by Tifaifai** [comment]
@mgdm Please merge this commit to the php8 branch!
It's OK with php8.2

**Pull request merged**
